### ISSUE TITLE
Change `require()` to ES `import`

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/grounding-search#11]

**Comment by metincansiper** [comment]
@maxkfranz  I am working on this but looks like we were using some patterns based on flexibility of `commonjs` and we will need to choose relinquish some benefits while switching to ES `import`/`export`.

The very first thing to consider is that ES export can be done in two ways:

- Named exports
```
// exports a function declared earlier
export { myFunction }; 

// exports a constant
export const foo = Math.sqrt(2);
```
- Default exports 
```
export default myFunction;
```

Named exports can be imported as:
```
import { myFunction } from 'mymodule'
```

Default exports can be imported as:
```
// name does not have to match in this case
import myFunction from 'mymodule'
```
However, the following combinations will give an error:
```
// module1
export default { prop1, prop2 }
// module2
// cause error because `module1` has only default export
// here prop1 looks for a named export
import {prop1} from 'module1'
```

```
// module1
export { prop1, prop2 }
// module2
import m1 from 'module1'
// cause error because module1 has not export default statement
// and m1 is assigned to whatever is in export default statement
// not to  { prop1, prop2 } in this case
m1.prop1 
```

The following is problematic as well:
```
// conf.js
let conf = ...// calculate configuration object here
export conf;
```
It can work with the following:
```
// conf.js
let conf = ...// calculate configuration object here
export { URL, ... } = conf;
```

In the current code we use both of the following ways (in commonjs style):
```
// first way
const { prop1, prop2 } = require('mymodule');
// second way
const mymodule = require('mymodule');
let pro1 = mymodule.prop1;
```

We have some patterns where the second way is very useful. Therefore, while converting to ES6 structure we need to make a choice that will relinquish some of the flexibilities that we had with commonjs. I beleive using the same structure/pattern throughout the whole code may be usefull to decrease confusions.

- We can always use export default (never use export): 
In this case we will need to use modules like the following:
```
import mymodule from `mymodule`
const { prop1, prop2 } = mymodule
// or
const prop1 = mymodule.prop1;
```
Note: In this case we may overcome the problem in conf.js without needing to write extra code  to export each variable.

- Anytime we export set of properties we can export an object including them all as default as well.

```
// The bad news here is that I cannot store { prop1, prop2 } in a variable and use it for both lines
// export will give error in that case. If i try "export const a = { prop1, prop2 }; export default a;"
// export will put object to `a` property so neither that will work
export { prop1, prop2 }
export default { prop1, prop2 }
```

These are the ways I am able to find. I think non is ideal but I suppose we need to choose one if we want to use ES import/export.

**Comment by maxkfranz** [comment]
I think it's best to use this:


```js
/**
* JSDoc
*/
export const foo = a => { /* ... */ };

/**
* JSDoc
*/
export const bar = b;
```

Basically, where the variable is assigned has both the `export` and JSDoc definition.  Apart from clear exceptions, we should probably avoid default exports.  The main exception would be where a module could only ever export one thing, but even then a named export is nice because it gives you a good hint about what the exported function does by the name.

**Comment by metincansiper** [comment]
@maxkfranz I think using that way looks good expect the concern I mentioned above. It was basically about we have some patterns like the followings:

https://github.com/PathwayCommons/grounding-search/blob/master/src/server/datasource/cli.js#L8

https://github.com/PathwayCommons/grounding-search/blob/master/test/util/datasource.js#L6

I think such implementations may require non ideal changes if we use named export for related modules. However, I realized that such usages are mostly helpful for datasources (including aggregate) and we most probably never use datasources in the other way. I suppose we do not have and will never need to have some imports like the following:

```
import { update } from 'uniprot'
```

I think we will always be calling it like `uniprot.update()` instead. Therefore, I think that the main problem can be solved if we include datasources (again including aggregate) as part of the modules that exports one thing and that thing is an object of functions (actually it was already object of functions with the existing commonjs implementation). We may consider them like `db.js`.

What do you think?

**Comment by maxkfranz** [comment]
The simplest option is probably to just do something like

```js
export const uniprot = { update, get, search };
```

**Comment by metincansiper** [comment]
I think it will not be solving the problem that I mentioned. If I export like that and then try to import it like `import uniprot from 'uniprot'` it will give an error. Then the pattern I sampled above will still not be usable as is.

**Comment by metincansiper** [comment]
BTW to clarify what I mean both of the followings will be exporting the same thing:

```
export const uniprot = { update, get, search };
```
```
export const update = ...;
export const get = ...;
export const search = ...;
```
 In both ways ``import uniprot from 'uniprot'`` will not work. It may work with the following:

```
export default { update, get, search };
```

**Comment by maxkfranz** [comment]
Yes, you'd have to do

```js
import { uniprot } from './uniprot';

// and then

const { get, search } = uniprot;

// or just use

uniprot.search();
```

**Comment by metincansiper** [comment]
@maxkfranz To make that example work I must have the following uniprot.js file

```
export const uniprot = { get, search };
// or
let uniprot = { get, search };
export uniprot;
```

If I will be exporting one main object would not it be more convenient to export it as default like the following:
```
export default { get, search };
```
Then use like the following:
```
import uniprot from './uniprot';

// and then

const { get, search } = uniprot;

// or just use

uniprot.search();
```

**Comment by metincansiper** [comment]
Actually maybe the way you mentioned is better for less confusion and maybe better for JSDOCs too, I will do it like that.

**Comment by metincansiper** [comment]
But actually exporting default looks more convenient to import because it gives more flexibility in naming without needing to use `as` and exporting in that way is easier since you do not have to define an object like `uniprot` in this case.

 However, anyways I am doing it like you mentioned for now unless we make a final decision on the other way.

**Comment by maxkfranz** [comment]
It's probably good to enforce consistency in the names anyway.  That way, you always know what you're looking at and things like find-replace work better.

**Comment by metincansiper** [comment]
@maxkfranz Okay I made the commit by following the way that we have decided on. BTW to fix the JSDOC scoping problem that we have previously talked about it was enough to add ``/** @module moduleName */`` to the beginning of the modules.

**Comment by metincansiper** [comment]
@maxkfranz I was not aware of `import * as name from "module-name";` syntax while we were having this discussion. I think that syntax may be useful for exporting/importing the objects that sometimes must be accessed as the whole object and sometimes the properties must directly be accessible (e.g. datasources like `uniprot`).

What we are currently doing is the fallowing:
```
import { uniprot } from './uniprot';

// and then

const { get, search } = uniprot;

// or just use

uniprot.search();
```

What we can do instead is:
```
import * as uniprot from  './uniprot' ;

uniprot.search();

// or

import { get, search } from './uniprot';

search();

```

In this way we can get rid of writing extra code like ``const { get, search } = uniprot;`` when we directly need the props like `get()` and `search()`.

What do you think?

**Comment by maxkfranz** [comment]
Sounds good, but it's not a high priority
