### ISSUE TITLE
Self-contained version of grounding service 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/grounding-search#112]
The issue is to create a (simple, stable) method to run a local instance of the grounding search service. 

- Must consider
  - Backed by an index (elasticsearch)
  - grounding data
  - environment variables and private API keys

### Notes

* Could also use this instance in prod (https://github.com/PathwayCommons/factoid-docker-config)?
* grounding search data (NCBI Gene, UniProt, ChEBI)  size ~500 MB.

**Comment by jvwong** [comment]
One possible route is 

1. Check-in the elasticsearch dump data (~500 MB)
2. Allow config to control 'refresh' of es dump files from Zenodo, default is use checked-in (possibly out of date) data

In this way, no API keys are required (NCBI key is needed to grab data for SARS-Cov2; Zenodo key is needed for download)

**Comment by maxkfranz** [comment]
It's usually not recommended to commit large files to git/github.

Shouldn't the Zenodo data be public already?  That's the point of Zenodo:  The data is public with a DOI.

An alternative would be a static site with Cloudflare, but I'd rather have the Zenodo data public.

**Comment by jvwong** [comment]
Yeah, the Zenodo key is only needed to push new data, so should be OK. I'm looking at this right now...

**Comment by jvwong** [comment]
README should contain:
  - simple instructions on running service starting from scratch
  - explanation of the grounding data available (zenodo)
    -  how to update manually
    - limitations of exiting data (support, use case)

**Comment by maxkfranz** [comment]
Also: Prominently list the CC0 license for the data in the readme
