### ISSUE TITLE
Restore index from Zenodo from Published data

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/grounding-search#113]
When restoring the grounding-search data (NCBI Gene, UniProt, CheBI) directly from Zenodo, the Zenodo source data (analyzer, mapping, data) should be published and the grounding search instance should be fetching from the public URL.

To this point, I was mistakenly keeping the source data on Zenodo unpublished, and using a URL that was private (API) and required authentication etc.

**Comment by gbader** [comment]
How often is this indexed updated?

**Comment by jvwong** [comment]
I pushed data to Zenodo for the first and only time on Feb 2 2021. Updates are done manually.

**Comment by gbader** [comment]
and how large is the file?

**Comment by jvwong** [comment]
There's 3 index files: 933 Bytes; 1 kB and 495.9 MB.
