### ISSUE TITLE
Add more protein/gene test cases from a popularity list

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/grounding-search#12]
There's a list somewhere that has the top N protein/gene names by popularity.  We could use that list in our tests.  Having good coverage for popular proteins is important.

@jvwong Do you remember where we can find this list?

**Comment by jvwong** [comment]
I mentioned the NCBI Gene database download file `gene2pubmed` (ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/) which is a tab-delimited with columns:

| tax_id | GeneID | PubMed_ID |
|------|------|--------|

**Comment by maxkfranz** [comment]
@jvwong All chebi ids need to be updated in your tests.

From: `{ namespace: 'chebi', id: '1234' }`

To: `{ namespace: 'chebi', id: '1234' }`

**Comment by jvwong** [comment]
OK done.
