### ISSUE TITLE
Grounding to yeast only

### ISSUE THREAD

**Issue by duncster94** [PathwayCommons/grounding-search#147]
Hi, thanks for providing this tool!

I have a set of Saccharomyces cerevisiae gene function papers that I'm performing NER on. I want to be able to ground entity mentions to yeast genes only. I talked to Gary and he mentioned this tool would be useful but would require a yeast-specific dictionary. How difficult would it be to set up grounding-search for yeast genes?

Thanks!

**Comment by jvwong** [comment]
I think this would be simple to accomplish. The assumption is you would run/deploy this via Docker (Compose) and access over HTTP. What's your timeline?

You play with a development instance at https://grounding.baderlab.org/

Caveats for this system:
  - You will get [NCBI Gene](https://www.ncbi.nlm.nih.gov/gene/) identifiers from
    - [Saccharomyces cerevisiae "parent"](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=4932&lvl=3&lin=f&keep=1&srchmode=1&unlock)
    - [Saccharomyces cerevisiae strains](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Tree&id=4932&lvl=3&keep=1&srchmode=1&unlock)
  - The system will (always) return a list of top hits 
    - Risk: It is not guaranteed the top hits are relevant (Work in progress)

**Comment by duncster94** [comment]
Hi Jeff, thanks for the quick reply.

No strict timeline but sooner is always better. Can you walk me through the step-by-step process of grounding to yeast? Gary mentioned the system isn't set up for yeast so it sounds like we would have to provide a dictionary containing yeast IDs and corresponding synonyms - is this correct?

Also, when you mention that the top hits are not always relevant - how widespread is this issue? Are there special cases where the hits are typically wrong that I should be aware of?

Thanks again.

**Comment by jvwong** [comment]
Also: https://joss.theoj.org/papers/10.21105/joss.03756

**Comment by duncster94** [comment]
Thanks Jeff. I'll try this out and let you know if I have any questions!

**Comment by duncster94** [comment]
Thanks Jeff. I'll try this out and let you know if I have any questions!

**Comment by jvwong** [comment]
Here's a quick solution - grab this [docker-compose.yml.zip](https://github.com/PathwayCommons/grounding-search/files/14140494/docker-compose.yml.zip) file then in the same directory type `docker-compose up -d`. 

Give it 5 minutes to index the dictionary, and then you should see the Swagger docs on http://localhost:3000/.

Assumes you (1)  have Docker (2) aren't running anything on port :3000 and (3) are not working on Apple silicon.
