### ISSUE TITLE
Search quality test cases

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/grounding-search#18]
The test cases need to be reviewed.  There are 898 test cases that evaluate the quality of the search results.  @jvwong has done a great job on the first pass of this data, but it's a lot of data  and it's easy to make small mistakes.

So, we should have each of the test cases reviewed to make sure that we have a solid basis for moving forward with improving the quality of the search.  So let's divvy it up:

- @cannin
  - [ ] http://dx.doi.org/10.1016/j.molcel.2017.01.019
  - [ ] http://dx.doi.org/10.1016/j.molcel.2016.12.018
  - [ ] https://doi.org/10.1016/j.molcel.2018.04.024
  - [ ] http://dx.doi.org/10.1016/j.molcel.2016.11.034
- @sacdallago 
  - [x] http://dx.doi.org/10.1016/j.molcel.2017.02.016
  - [x] http://dx.doi.org/10.1016/j.molcel.2017.01.027
  - [x] https://doi.org/10.1016/j.molcel.2018.08.014
- @emekdemir 's team
  - [ ] https://doi.org/10.1016/j.molcel.2017.11.025
  - [ ] http://dx.doi.org/10.1016/j.molcel.2016.12.021
  - [ ] http://dx.doi.org/10.1016/j.molcel.2013.11.004

Steps:

- [ ] Make a separate branch or fork for your work.
- [ ] In your branch or fork, make commits to revise erroneous expected groundings in `test/util/data/molecular-cell.json`.
- [ ] Make sure the `organismOrdering` is specified for the paper.  If the paper is about one organism, say human, it should be `"organismOrdering": [9606]`.  If the paper is about human mostly but also a little about mouse, then it should be `"organismOrdering": [9606, 10090]`.
- [ ] Make a PR when you're done.

**Comment by maxkfranz** [comment]
@emekdemir I've updated the list.

**Comment by sacdallago** [comment]
@maxkfranz questions from @cannin and myself:

- If `null`, should we correct the grounding?
- If no `organismOrdering ` is present (never is), should we manually add it?


Thank you.

**Comment by jvwong** [comment]
Yeah sure but some of those were 'family' members or 'complexes' so beware.

**Comment by maxkfranz** [comment]
For `organismOrdering`, you should always specify it.  It should be the list of organisms relevant to the paper in order of decreasing relevance.  For most papers, there will be only one taxon ID in the list.

For `null` cases, you should specify it only if the expected grounding exists for NCBI or Chebi --- genes/gene-products or chemicals.

**Comment by cannin** [comment]
@maxkfranz where should the organismOrdering go (there are no current examples in the file)? 

    [
      {
       "id": "http://dx.doi.org/10.1016/j.molcel.2017.01.019",
       "entities": [
        {
         "text": "RUVBL1",
         "xref_id": "8607",
         "namespace": "ncbi",
         "sentence": "PRMT5 Dependent Methylation of the TIP60 Coactivator RUVBL1 Is a Key Regulator of Homologous Recombination  Volume 65 , Issue 5 , 2 March 2017 , Pages 900-916  Thomas L. Clarke , Maria Pilar Sanchez-Bailon , Kelly Chiang , John J. Reynolds , Joaquin Herrero-Ruiz , Tiago M. Bandeiras , Pedro M. Matias , Sarah L. Maslen , J. Mark Skehel , Grant S.Stewart , Clare C. Davies  Summary  Protein post-translation modification plays an important role in regulating DNA repair ; however , the role of arginine methylation in this process is poorly understood ."
        },
    ...

**Comment by maxkfranz** [comment]
It works either per-group or per-entity, but you should probably set it on the paper (group) level beside `entities`.  A paper should probably only have a single organism ordering preference.

**Comment by sacdallago** [comment]
Also: we don't _add_ groundings, right? If we see things that are not picked up: that's just life... correct? Because boy is stuff missed....

**Comment by jvwong** [comment]
You can add whatever you want. I used REACH to pull out entities so yeah, it's just a first pass.

**Comment by sacdallago** [comment]
Well, for now all of the groundings are correct (I've just added the organism ids). Adding entities is a different story, I'd have to spend another weekend on it...
