### ISSUE TITLE
Swagger docs

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/grounding-search#4]
The docs should be shown on the main index.html on the server.

**Comment by metincansiper** [comment]
@maxkfranz I did not use html file to show the docs because I think using so would have been requiring to include js libs from html and I wanted to avoid that. I put the docs to /api/docs and redirected there from the root. However, if you think using index.html is strictly needed I can do so.

**Comment by maxkfranz** [comment]
The location doesn't matter that much right now
