### ISSUE TITLE
Add support for model organisms other than human

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/grounding-search#5]

**Comment by metincansiper** [comment]
@maxkfranz Should all of the organizms be enabled with no check at all? Or only the ones supported by factoid (https://github.com/PathwayCommons/factoid/blob/master/src/model/organism.js#L59) must be enabled (I am actually not sure if the factoid already support all organisms)?

**Comment by maxkfranz** [comment]
Let's start with just the list that Factoid supports.

**Comment by metincansiper** [comment]
Okay, I did so. Looks like nothing is broken after the related commit.

**Comment by metincansiper** [comment]
However, as far as I can understand these organism ids are not specific to uniprot. If that is true it would make sense if I  move supported organism ids list to a more general file from the uniprot file.

**Comment by maxkfranz** [comment]
Yes, they're taxon ids -- which are not specific to uniprot.

**Comment by metincansiper** [comment]
Okay, thanks. I updated as I mentioned.
