### ISSUE TITLE
Quality tests: Remove 'loose'; make output reporting easier      

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/grounding-search#51]
I want to update the `aggregate-quality.js` code to make reporting a little easier. 

In particular, I want to get rid of the 'loose' values which tend to bury useful information (i.e. rank). Rather, all of this can be assessed  at the reporting stage by outputting things like rank (somewhere). 

Also need some sort of custom reporter, since most times want report in csv form for a spreadsheet.

**Comment by maxkfranz** [comment]
You can output json: https://mochajs.org/#json

**Comment by maxkfranz** [comment]
https://github.com/mochajs/mocha/wiki/Third-party-reporters
