### ISSUE TITLE
NCBI: Capture additional metadata fields

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/grounding-search#63]
Goal is to capture additional NCBI Gene metadata fields that can be useful for downstream data consumers including data export (BioPAX) and software (Factoid).

In particular, the NCBI `gene_info` file contains 

1. `dbXrefs`: ID-mappings to external organism databases (e.g. HGNC - human, Araport - Arabadopsis, FLYBASE - Drosophila) 
2. `type_of_gene`: This is a description of the gene's products (e.g. tRNA, ncRNA, protein-coding etc.)

Example: The non-coding RNA gene 

|         tax_id     | GeneID |    Symbol |                     dbXrefs | type_of_gene |
|--------------|-----------|---------|-----------------|-------------|
|    9606|  102800311|  TP53COR1 |  MIM:616343\|HGNC:HGNC:43652        | ncRNA|

Docs:

https://www.ncbi.nlm.nih.gov/data_specs/dtd/NCBI_Entrezgene.mod.dtd
```xml
<!ELEMENT Entrezgene_type (%INTEGER;)>
<!ATTLIST Entrezgene_type value (
        unknown |
        tRNA |
        rRNA |
        snRNA |
        scRNA |
        snoRNA |
        protein-coding |
        pseudo |
        transposon |
        miscRNA |
        ncRNA |
        biological-region |
        other
        ) #IMPLIED >
```

**Comment by maxkfranz** [comment]
Note: A grounding entry is stored within Factoid at the time of grounding.  This means you'd need a mechanism to refresh the groundings in old documents.
