### ISSUE TITLE
Signal if datasource update failure has occurred

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/grounding-search#76]
Background: When data sources are indexed, they mail fail either partially or entirely. For instance, the source file may not be downloaded. In this case, the build continues to the next source regardless of the integrity of the data in the index. 

Goal: It would be helpful to signal that a failure has occurred so that further action can be performed to correct the issue (i.e. rerun or inspect the problem) 

Details: The issue can occur with build locally, but more importantly, Docker images, which 'fail silently'.

**Comment by jvwong** [comment]
So I'm reopening this because of an edge case that we specifically ignore last time: The datasource file is downloaded, but there is nothing in it. 

- This happened to day where `input/chebi.owl` is downloaded successfully, exists but is empty

**Comment by jvwong** [comment]
Maybe we should check-in in a fallback version of ncbi gene and chebi just in case?

**Comment by maxkfranz** [comment]
Git doesn't handle large files well.  How about a simple file size check?  Throw an error if it's empty or very small?

**Comment by maxkfranz** [comment]
Another option is manually uploading the files to Zenodo.

**Comment by jvwong** [comment]
Since we only boot prod manually and periodically, I can just detect whether the download was non-zero in size.
