### ISSUE TITLE
Real users: Misc observations

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/grounding-search#84]
- Why is the correct grounding for query not returned in the search results?
  - Query term: `TGF-beta receptor`
  - Observed: https://identifiers.org/ncbigene:30739
  - Expected: https://www.ncbi.nlm.nih.gov/gene/7048; not present in returned list

**Comment by maxkfranz** [comment]
<img width="445" alt="Screen Shot 2020-10-06 at 1 56 21 PM" src="https://user-images.githubusercontent.com/989043/95241444-bfadc200-07db-11eb-8c89-011291fcfcc2.png">

There is no 'TGF-beta receptor' synonym for human in NCBI.

**Comment by maxkfranz** [comment]
Is 'receptor' a keyword that could just be omitted from the search?

**Comment by maxkfranz** [comment]
There should be an added synonym in the patch file for cofilin-1 (human) as 'cofilin'.  See https://biofactoid.org/document/aa18ee18-a78f-4d46-a244-9a6dc97bb238

**Comment by jvwong** [comment]
> Is 'receptor' a keyword that could just be omitted from the search?

Let me clarify my issue: I search for `TGF-beta receptor` and 18 results come back. None of them include:

```json
{
  "namespace": "ncbi",
  "type": "ggp",
  "dbName": "NCBI Gene",
  "dbPrefix": "ncbigene",
  "id": "7048",
  "organism": "9606",
  "organismName": "Homo sapiens",
  "name": "TGFBR2",
  "synonyms": [
    "AAT3",
    "FAA3",
    "LDS1B",
    "LDS2",
    "LDS2B",
    "MFS2",
    "RIIC",
    "TAAD2",
    "TBR-ii",
    "TBRII",
    "TGFR-2",
    "TGFbeta-RII",
    "TGF-beta receptor type-2",
    "TGF-beta receptor type IIB",
    "TGF-beta type II receptor",
    "tbetaR-II",
    "transforming growth factor beta receptor II",
    "transforming growth factor beta receptor type IIC",
    "transforming growth factor, beta receptor II (70/80kDa)",
    "transforming growth factor, beta receptor II alpha",
    "transforming growth factor, beta receptor II beta",
    "transforming growth factor, beta receptor II delta",
    "transforming growth factor, beta receptor II epsilon",
    "transforming growth factor, beta receptor II gamma",
    "transforming growth factor beta receptor 2"
  ],
  "dbXrefs": [
    ...
  ],
  "typeOfGene": "protein-coding"
}
```

**Comment by maxkfranz** [comment]
It's way too bad of a match to be included.

The options are:

(1) Add a synonym to the patch file s.t. 'receptor' is part of the name.

(2) Remove the keyword 'receptor' from all search queries.  Then 'tgf beta receptor' becomes 'tgf beta' and is a good match.

**Comment by maxkfranz** [comment]
Re (1), you'd need this synonym: 'TGF-beta receptor'

**Comment by maxkfranz** [comment]
Another thing to consider is that a query like 'TGF beta receptor' would be a better fit for a protein family grounding.

**Comment by jvwong** [comment]
the confusing thing is that this is the top human searchHit (rank 3):

```
{
    "namespace": "ncbi",
    "type": "ggp",
    "dbName": "NCBI Gene",
    "dbPrefix": "ncbigene",
    "id": "5737",
    "organism": "9606",
    "organismName": "Homo sapiens",
    "name": "PTGFR",
    "synonyms": [
      "FP",
      "prostaglandin F2-alpha receptor",
      "FP prostanoid receptor",
      "PGF receptor",
      "PGF2 alpha receptor",
      "prostaglandin receptor (2-alpha)",
      "prostanoid FP receptor",
      "prostaglandin F receptor"
    ],
```

**Comment by maxkfranz** [comment]
'PGF receptor' is only off by two, whereas your preferred grounding is off by way more.

If the NCBI synonyms are insufficient for user input, then there needs to be more curation effort on the patch file to include real-world, human-entered synonyms.  Or, we need to find a better database of synonyms.

For 'TGF beta receptor', I'm not convinced the grounding should be tgfb2 instead of tgfb1 -- or that it shouldn't just be the protein family.

**Comment by maxkfranz** [comment]
Character diff:

```
TGFb receptor
PGF   receptor
```

**Comment by maxkfranz** [comment]
Initial thoughts:  It’s a long search query that probably doesn’t match any synonym closely. The user didn’t specify a synonym, they specified what looks like a combination of synonyms. On Oct 6, 2020, at 13:52, Jeffrey ***@***.***> wrote:﻿

Why is the correct grounding for query not returned in the search results?

Query term: TGF-beta receptor
Observed: https://identifiers.org/ncbigene:30739
Expected: https://www.ncbi.nlm.nih.gov/gene/7048; not present in returned list
