### ISSUE TITLE
Index UniProt: Xrefs; namepaces

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/grounding-search#88]
> Next steps:
> 
> Grounding service updates:
> 
>     1. Reenable Uniprot within the grounding service. [JVW]
> 
>     2. Add an option to the aggregate search (i.e. `/search`) s.t. namespaces can be blocked (i.e. uniprot namespaces aren't returned to Biofactoid UI).  This can accept an option to set the block list manually, but we will have a default value s.t. uniprot is blocked by default. [MF]
> 
>     3. In the uniprot importer, the xrefs need to be included in the returned grounding json.  [JVW]
> 
> 
> Convertor pipeline: [MCS]
> 
>     1. Within the PC import, instead of doing a `/search` (today), do a `/get` (e.g. `/get` for `uniprot:P01234`).
> 
>     2. Now, you have a uniprot grounding.  So, within it, get the NCBI xref.
> 
>     3. Query `/get` with the NCBI xref.
> 
>     4. Use the NCBI grounding for the factoid entity in the `association`.
> 
> 
> Once done: Run the import on the master.factoid.baderlab.org instance. Merge the data into

Refs: https://github.com/PathwayCommons/factoid/pull/881#issuecomment-713090812

**Comment by maxkfranz** [comment]
See (2) in #90
