### ISSUE TITLE
xml-parser: omitList considers only open tag and not closing

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/grounding-search#89]
Background: The xml-parser provides an `omitList` that intends to skip certain tags by name

Issue: The parser considers the `omitList` upon encountering an open tag, but not the closing tag. This leads to skipping large sections of the tree.

Prerequisite for #88

**Comment by jvwong** [comment]
I gather the intention of omitList was to skip a tag including its children, however, currently it is ignoring an open tag.

**Comment by maxkfranz** [comment]
Do you mean self closing tags, e.g. `<foo bar="baz" />`?

**Comment by jvwong** [comment]
No, the self-closing tags are properly handled. The code was skipping an omitted tag but then still including its children and not keeping track of the skipped tag etc.
